<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 SabreDav Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(); ?>

        <!-- Scripts -->
        <?php echo $this->headScript(); ?>

    </head>
    <body>
        <?php echo $this->content; ?>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
